// Generated by gencpp from file ArmControl/ArmMotorCommand.msg
// DO NOT EDIT!


#ifndef ARMCONTROL_MESSAGE_ARMMOTORCOMMAND_H
#define ARMCONTROL_MESSAGE_ARMMOTORCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ArmControl
{
template <class ContainerAllocator>
struct ArmMotorCommand_
{
  typedef ArmMotorCommand_<ContainerAllocator> Type;

  ArmMotorCommand_()
    : MotorVel()  {
      MotorVel.assign(0);
  }
  ArmMotorCommand_(const ContainerAllocator& _alloc)
    : MotorVel()  {
  (void)_alloc;
      MotorVel.assign(0);
  }



   typedef boost::array<int8_t, 6>  _MotorVel_type;
  _MotorVel_type MotorVel;





  typedef boost::shared_ptr< ::ArmControl::ArmMotorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ArmControl::ArmMotorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ArmMotorCommand_

typedef ::ArmControl::ArmMotorCommand_<std::allocator<void> > ArmMotorCommand;

typedef boost::shared_ptr< ::ArmControl::ArmMotorCommand > ArmMotorCommandPtr;
typedef boost::shared_ptr< ::ArmControl::ArmMotorCommand const> ArmMotorCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ArmControl::ArmMotorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ArmControl::ArmMotorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ArmControl::ArmMotorCommand_<ContainerAllocator1> & lhs, const ::ArmControl::ArmMotorCommand_<ContainerAllocator2> & rhs)
{
  return lhs.MotorVel == rhs.MotorVel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ArmControl::ArmMotorCommand_<ContainerAllocator1> & lhs, const ::ArmControl::ArmMotorCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ArmControl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ArmControl::ArmMotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ArmControl::ArmMotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmControl::ArmMotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ArmControl::ArmMotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmControl::ArmMotorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ArmControl::ArmMotorCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ArmControl::ArmMotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e57f9e32cb43e25c5210a7f3aace40d5";
  }

  static const char* value(const ::ArmControl::ArmMotorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe57f9e32cb43e25cULL;
  static const uint64_t static_value2 = 0x5210a7f3aace40d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ArmControl::ArmMotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ArmControl/ArmMotorCommand";
  }

  static const char* value(const ::ArmControl::ArmMotorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ArmControl::ArmMotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[6] MotorVel\n"
"\n"
;
  }

  static const char* value(const ::ArmControl::ArmMotorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ArmControl::ArmMotorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.MotorVel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmMotorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ArmControl::ArmMotorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ArmControl::ArmMotorCommand_<ContainerAllocator>& v)
  {
    s << indent << "MotorVel[]" << std::endl;
    for (size_t i = 0; i < v.MotorVel.size(); ++i)
    {
      s << indent << "  MotorVel[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.MotorVel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMCONTROL_MESSAGE_ARMMOTORCOMMAND_H
